#!/bin/sh

for id in $(seq 50); do 
	if [ ! -z "$(xinput list-props $id 2>/dev/null | grep 'libinput Accel Profile Enabled (')" ]; then
		xinput --set-prop $id 'libinput Accel Profile Enabled' 0, 1 && echo 'Changing Accel Profile for <device id '"$id"'> to (0, 1)'
	fi
done

setkbmap fr

picom -f &
$HOME/.config/polybar/launch
wal -R

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

. $HOME/.cache/wal/colors.sh
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"